# Generated by Django 4.2 on 2023-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('description', models.TextField(max_length=500, null=True)),
                ('pic', models.ImageField(null=True, upload_to='festival_images')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
