# Generated by Django 4.2 on 2023-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
