# Generated by Django 4.2 on 2023-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_events_event_date_alter_events_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(default='description', max_length=500, null=True),
        ),
    ]
