# Generated by Django 4.2 on 2023-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_events_user_alter_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(default='Nill', max_length=500),
        ),
    ]
