# Generated by Django 4.2 on 2023-05-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_expiredevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiredEvents',
        ),
    ]
