# Generated by Django 4.2 on 2023-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_expiredevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('description', models.TextField(default='Nill', max_length=500)),
                ('pic', models.ImageField(null=True, upload_to='festival_images')),
                ('date', models.DateField(auto_now_add=True)),
                ('expireddate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
