# Generated by Django 4.2 on 2023-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_expiredevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiredEvents',
        ),
    ]
