# Generated by Django 4.2 on 2023-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_expiredevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribedusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
