# Generated by Django 4.2 on 2023-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
